### PR TITLE
fix duplicate DA record processing

### PR DESCRIPTION
**Pull request by jandelgado**
Fixes problem reported here: https://github.com/jandelgado/gcov2lcov-action/issues/2

### CODE REVIEW

**Comment by arvenil** [comment]
@jandelgado One of builds just returned 100% code coverage. I think not :)

Lines that are not covered got counted as lines that don't need coverage.

Check it here: 
* https://coveralls.io/builds/30340173/source?filename=bsearch/interpolation.go#L16

And proof: 
* https://codecov.io/gh/arvenil/kata/src/86c5744a87aca1a0b2443a173eeb6cbc0eb331af/bsearch/interpolation.go#L16

Could it be this fix?

**Comment by jandelgado** [comment]
@arvenil  Could you please post the go-coverage output for the mentioned test? I'll check if it is converted correctly to lcov format

**Comment by jandelgado** [comment]
@arvenil  Could you please post the go-coverage output for the mentioned test? I'll check if it is converted correctly to lcov format 

Btw: if I look at https://coveralls.io/builds/30340173/source?filename=bsearch/interpolation.go#L4 it seems that the 100% reported test coverage is **not** consistent with the source code shown, where not every line is covered. Might be a problem in coveralls?

**Comment by arvenil** [comment]
Here are the files.
[coverage.lcov.zip](https://github.com/jandelgado/gcov2lcov/files/4535082/coverage.lcov.zip)
[coverage.out.zip](https://github.com/jandelgado/gcov2lcov/files/4535083/coverage.out.zip)

Checking now https://github.com/jandelgado/gcov2lcov/pull/4

**Pull request merged**
